//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymTrack.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class English {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal English() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GymTrack.Resources.Languages.English", typeof(English).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12 H.
        /// </summary>
        public static string AppSW_12formatComboboxItem {
            get {
                return ResourceManager.GetString("AppSW_12formatComboboxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12-hour format: AM/PM format.
        /// </summary>
        public static string AppSW_12formatDescription {
            get {
                return ResourceManager.GetString("AppSW_12formatDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24 H.
        /// </summary>
        public static string AppSW_24formatComboboxItem {
            get {
                return ResourceManager.GetString("AppSW_24formatComboboxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24-hour format: without AM or PM.
        /// </summary>
        public static string AppSW_24formatDescription {
            get {
                return ResourceManager.GetString("AppSW_24formatDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barbie.
        /// </summary>
        public static string AppSW_barbieThemeComboboxItem {
            get {
                return ResourceManager.GetString("AppSW_barbieThemeComboboxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every night is girls&apos; night.
        /// </summary>
        public static string AppSW_barbieThemeDescription {
            get {
                return ResourceManager.GetString("AppSW_barbieThemeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current path:.
        /// </summary>
        public static string AppSW_currentTrainingsFolderText {
            get {
                return ResourceManager.GetString("AppSW_currentTrainingsFolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string AppSW_darkThemeComboboxItem {
            get {
                return ResourceManager.GetString("AppSW_darkThemeComboboxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark background, lighter foreground. For dark theme enjoyers.
        /// </summary>
        public static string AppSW_darkThemeDescription {
            get {
                return ResourceManager.GetString("AppSW_darkThemeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string AppSW_engLanguageComboboxItem {
            get {
                return ResourceManager.GetString("AppSW_engLanguageComboboxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classical English language.
        /// </summary>
        public static string AppSW_engLanguageDescription {
            get {
                return ResourceManager.GetString("AppSW_engLanguageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export your app settings.
        /// </summary>
        public static string AppSW_exportAppSettingsButtonContent {
            get {
                return ResourceManager.GetString("AppSW_exportAppSettingsButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export your app settings:.
        /// </summary>
        public static string AppSW_exportSettingsTextBlock {
            get {
                return ResourceManager.GetString("AppSW_exportSettingsTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose new folder.
        /// </summary>
        public static string AppSW_folderButtonContent {
            get {
                return ResourceManager.GetString("AppSW_folderButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hacker.
        /// </summary>
        public static string AppSW_hackerThemeComboboxItem {
            get {
                return ResourceManager.GetString("AppSW_hackerThemeComboboxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark background, mostly green foreground. For hacking stereotypes enjoyers.
        /// </summary>
        public static string AppSW_hackerThemeDescription {
            get {
                return ResourceManager.GetString("AppSW_hackerThemeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure GymTrack however you like!.
        /// </summary>
        public static string AppSW_header {
            get {
                return ResourceManager.GetString("AppSW_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import app settings.
        /// </summary>
        public static string AppSW_importAppSettingsButtonContent {
            get {
                return ResourceManager.GetString("AppSW_importAppSettingsButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locate app configuration file:.
        /// </summary>
        public static string AppSW_importSettingsTextBlock {
            get {
                return ResourceManager.GetString("AppSW_importSettingsTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        public static string AppSW_languageTextBlock {
            get {
                return ResourceManager.GetString("AppSW_languageTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string AppSW_lightThemeComboboxItem {
            get {
                return ResourceManager.GetString("AppSW_lightThemeComboboxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light background, darker foreground. For light theme enjoyers.
        /// </summary>
        public static string AppSW_lightThemeDescription {
            get {
                return ResourceManager.GetString("AppSW_lightThemeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Літературна українська.
        /// </summary>
        public static string AppSW_literatureUkrLanguageComboboxItem {
            get {
                return ResourceManager.GetString("AppSW_literatureUkrLanguageComboboxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чиста українська мова.
        /// </summary>
        public static string AppSW_literatureUkrLanguageDescription {
            get {
                return ResourceManager.GetString("AppSW_literatureUkrLanguageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oppenheimer.
        /// </summary>
        public static string AppSW_oppenheimerThemeComboboxItem {
            get {
                return ResourceManager.GetString("AppSW_oppenheimerThemeComboboxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am become death, the destroyer of worlds.
        /// </summary>
        public static string AppSW_oppenheimerThemeDescription {
            get {
                return ResourceManager.GetString("AppSW_oppenheimerThemeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Розмовна українська.
        /// </summary>
        public static string AppSW_spokenUkrLanguageComboboxItem {
            get {
                return ResourceManager.GetString("AppSW_spokenUkrLanguageComboboxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файна мова з підколами.
        /// </summary>
        public static string AppSW_spokenUkrLanguageDescription {
            get {
                return ResourceManager.GetString("AppSW_spokenUkrLanguageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme:.
        /// </summary>
        public static string AppSW_themeTextBlock {
            get {
                return ResourceManager.GetString("AppSW_themeTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time format:.
        /// </summary>
        public static string AppSW_timeFormatTextBlock {
            get {
                return ResourceManager.GetString("AppSW_timeFormatTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training data folder path:.
        /// </summary>
        public static string AppSW_trainingFolderPathTextBlock {
            get {
                return ResourceManager.GetString("AppSW_trainingFolderPathTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Settings.
        /// </summary>
        public static string AppSW_windowTitle {
            get {
                return ResourceManager.GetString("AppSW_windowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fri.
        /// </summary>
        public static string ASW_dayoffsFriday {
            get {
                return ResourceManager.GetString("ASW_dayoffsFriday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will rest on: .
        /// </summary>
        public static string ASW_dayoffsInfoTextBlock {
            get {
                return ResourceManager.GetString("ASW_dayoffsInfoTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will have to train every day.
        /// </summary>
        public static string ASW_dayoffsInfoTextBlockDefault {
            get {
                return ResourceManager.GetString("ASW_dayoffsInfoTextBlockDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mon.
        /// </summary>
        public static string ASW_dayoffsMonday {
            get {
                return ResourceManager.GetString("ASW_dayoffsMonday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sat.
        /// </summary>
        public static string ASW_dayoffsSaturday {
            get {
                return ResourceManager.GetString("ASW_dayoffsSaturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sun.
        /// </summary>
        public static string ASW_dayoffsSunday {
            get {
                return ResourceManager.GetString("ASW_dayoffsSunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training-free days:.
        /// </summary>
        public static string ASW_dayoffsTextBlock {
            get {
                return ResourceManager.GetString("ASW_dayoffsTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thu.
        /// </summary>
        public static string ASW_dayoffsThursday {
            get {
                return ResourceManager.GetString("ASW_dayoffsThursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tue.
        /// </summary>
        public static string ASW_dayoffsTuesday {
            get {
                return ResourceManager.GetString("ASW_dayoffsTuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wed.
        /// </summary>
        public static string ASW_dayoffsWednesday {
            get {
                return ResourceManager.GetString("ASW_dayoffsWednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export your account settings.
        /// </summary>
        public static string ASW_exportAccountButtonContent {
            get {
                return ResourceManager.GetString("ASW_exportAccountButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export your account settings:.
        /// </summary>
        public static string ASW_exportAccountTextBlock {
            get {
                return ResourceManager.GetString("ASW_exportAccountTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        public static string ASW_friday {
            get {
                return ResourceManager.GetString("ASW_friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account center.
        /// </summary>
        public static string ASW_header {
            get {
                return ResourceManager.GetString("ASW_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an account or import existing one!.
        /// </summary>
        public static string ASW_headerNoAccount {
            get {
                return ResourceManager.GetString("ASW_headerNoAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import an existing account.
        /// </summary>
        public static string ASW_importAccountButtonContent {
            get {
                return ResourceManager.GetString("ASW_importAccountButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locate account configuration file:.
        /// </summary>
        public static string ASW_importAccountTextBlock {
            get {
                return ResourceManager.GetString("ASW_importAccountTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        public static string ASW_monday {
            get {
                return ResourceManager.GetString("ASW_monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter your name.
        /// </summary>
        public static string ASW_nameEntryError {
            get {
                return ResourceManager.GetString("ASW_nameEntryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string ASW_nameTextBlock {
            get {
                return ResourceManager.GetString("ASW_nameTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your name here.
        /// </summary>
        public static string ASW_nameTextBox {
            get {
                return ResourceManager.GetString("ASW_nameTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        public static string ASW_saturday {
            get {
                return ResourceManager.GetString("ASW_saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        public static string ASW_sunday {
            get {
                return ResourceManager.GetString("ASW_sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        public static string ASW_thursday {
            get {
                return ResourceManager.GetString("ASW_thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        public static string ASW_tuesday {
            get {
                return ResourceManager.GetString("ASW_tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        public static string ASW_wednesday {
            get {
                return ResourceManager.GetString("ASW_wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter your weight properly.
        /// </summary>
        public static string ASW_weightEntryError {
            get {
                return ResourceManager.GetString("ASW_weightEntryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight:.
        /// </summary>
        public static string ASW_weightTextBlock {
            get {
                return ResourceManager.GetString("ASW_weightTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your weight here (optional).
        /// </summary>
        public static string ASW_weightTextBoxDefault {
            get {
                return ResourceManager.GetString("ASW_weightTextBoxDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track my weight.
        /// </summary>
        public static string ASW_weightTrackTextBlock {
            get {
                return ResourceManager.GetString("ASW_weightTrackTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Settings.
        /// </summary>
        public static string ASW_windowTitle {
            get {
                return ResourceManager.GetString("ASW_windowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string editButtonEditModeContent {
            get {
                return ResourceManager.GetString("editButtonEditModeContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string editButtonSaveModeContent {
            get {
                return ResourceManager.GetString("editButtonSaveModeContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom property(e.g. repetitions/seconds).
        /// </summary>
        public static string ExerciseDto_customPropertyPrompt {
            get {
                return ResourceManager.GetString("ExerciseDto_customPropertyPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exercise description.
        /// </summary>
        public static string ExerciseDto_descriptionPrompt {
            get {
                return ResourceManager.GetString("ExerciseDto_descriptionPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exercise title.
        /// </summary>
        public static string ExerciseDto_titlePrompt {
            get {
                return ResourceManager.GetString("ExerciseDto_titlePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets count:.
        /// </summary>
        public static string exerciseMainInfoSetsText {
            get {
                return ResourceManager.GetString("exerciseMainInfoSetsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill all required fields.
        /// </summary>
        public static string fillFieldsErrorMessage {
            get {
                return ResourceManager.GetString("fillFieldsErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data specifying required.
        /// </summary>
        public static string fillFieldsErrorTitle {
            get {
                return ResourceManager.GetString("fillFieldsErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON file.
        /// </summary>
        public static string jsonFileTitle {
            get {
                return ResourceManager.GetString("jsonFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Main Menu.
        /// </summary>
        public static string mainMenuButtonContent {
            get {
                return ResourceManager.GetString("mainMenuButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Account.
        /// </summary>
        public static string MW_accountButtonContent {
            get {
                return ResourceManager.GetString("MW_accountButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analytics.
        /// </summary>
        public static string MW_analyticsButtonContent {
            get {
                return ResourceManager.GetString("MW_analyticsButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to exit?.
        /// </summary>
        public static string MW_exitConfirmationText {
            get {
                return ResourceManager.GetString("MW_exitConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit the app.
        /// </summary>
        public static string MW_exitConfirmationTitle {
            get {
                return ResourceManager.GetString("MW_exitConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no training programs yet. Add one and begin your sport journey!.
        /// </summary>
        public static string MW_noTrainingsText {
            get {
                return ResourceManager.GetString("MW_noTrainingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string MW_openTrainingButtonContent {
            get {
                return ResourceManager.GetString("MW_openTrainingButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MW_settingsButtonContent {
            get {
                return ResourceManager.GetString("MW_settingsButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Training.
        /// </summary>
        public static string MW_trainingButtonContent {
            get {
                return ResourceManager.GetString("MW_trainingButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome, .
        /// </summary>
        public static string MW_welcomeText {
            get {
                return ResourceManager.GetString("MW_welcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Menu.
        /// </summary>
        public static string MW_windowTitle {
            get {
                return ResourceManager.GetString("MW_windowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please save all the data you are currently editing.
        /// </summary>
        public static string saveDataErrorMessage {
            get {
                return ResourceManager.GetString("saveDataErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data saving required.
        /// </summary>
        public static string saveDataErrorTitle {
            get {
                return ResourceManager.GetString("saveDataErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings not exported. Please, try again.
        /// </summary>
        public static string settingsExportErrorMessage {
            get {
                return ResourceManager.GetString("settingsExportErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export error.
        /// </summary>
        public static string settingsExportErrorTitle {
            get {
                return ResourceManager.GetString("settingsExportErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read from provided file.
        /// </summary>
        public static string settingsImportErrorMessage {
            get {
                return ResourceManager.GetString("settingsImportErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong or corrupted configuration file.
        /// </summary>
        public static string settingsImportErrorTitle {
            get {
                return ResourceManager.GetString("settingsImportErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *All the data is yours. It is stored only locally on your device.
        /// </summary>
        public static string settingsSubHeader {
            get {
                return ResourceManager.GetString("settingsSubHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comp. time.
        /// </summary>
        public static string StatW_compTimeStatButtonContent {
            get {
                return ResourceManager.GetString("StatW_compTimeStatButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completion time of trainings.
        /// </summary>
        public static string StatW_compTimeStatHeaderPart {
            get {
                return ResourceManager.GetString("StatW_compTimeStatHeaderPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enforceability.
        /// </summary>
        public static string StatW_enforceabilityStatButtonContent {
            get {
                return ResourceManager.GetString("StatW_enforceabilityStatButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enforceability (trainings count).
        /// </summary>
        public static string StatW_enforceabilityTimeStatHeaderPart {
            get {
                return ResourceManager.GetString("StatW_enforceabilityTimeStatHeaderPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics:.
        /// </summary>
        public static string StatW_headerPart1 {
            get {
                return ResourceManager.GetString("StatW_headerPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no data to form statistics from.
        /// </summary>
        public static string StatW_noDataText {
            get {
                return ResourceManager.GetString("StatW_noDataText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets.
        /// </summary>
        public static string StatW_setsStatButtonContent {
            get {
                return ResourceManager.GetString("StatW_setsStatButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum of sets.
        /// </summary>
        public static string StatW_setsStatHeaderPart {
            get {
                return ResourceManager.GetString("StatW_setsStatHeaderPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string StatW_weightStatButtonContent {
            get {
                return ResourceManager.GetString("StatW_weightStatButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes in your weight.
        /// </summary>
        public static string StatW_weightTimeStatHeaderPart {
            get {
                return ResourceManager.GetString("StatW_weightTimeStatHeaderPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string StatW_windowTitle {
            get {
                return ResourceManager.GetString("StatW_windowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings exported successfully.
        /// </summary>
        public static string successfullSettingsExportMessage {
            get {
                return ResourceManager.GetString("successfullSettingsExportMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export successful.
        /// </summary>
        public static string successfullSettingsExportTitle {
            get {
                return ResourceManager.GetString("successfullSettingsExportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings imported successfully.
        /// </summary>
        public static string successfullSettingsImportMessage {
            get {
                return ResourceManager.GetString("successfullSettingsImportMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import successful.
        /// </summary>
        public static string successfullSettingsImportTitle {
            get {
                return ResourceManager.GetString("successfullSettingsImportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string TCompW_cancelButtonContent {
            get {
                return ResourceManager.GetString("TCompW_cancelButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string TCompW_confirmButtonContent {
            get {
                return ResourceManager.GetString("TCompW_confirmButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark training as completed.
        /// </summary>
        public static string TCompW_windowTitle {
            get {
                return ResourceManager.GetString("TCompW_windowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter training title here.
        /// </summary>
        public static string TrainingDto_trainingTitlePrompt {
            get {
                return ResourceManager.GetString("TrainingDto_trainingTitlePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minute.
        /// </summary>
        public static string Transformer_infoTextMinute {
            get {
                return ResourceManager.GetString("Transformer_infoTextMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        public static string Transformer_infoTextMinutes {
            get {
                return ResourceManager.GetString("Transformer_infoTextMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exercises in total, estimated rest time:.
        /// </summary>
        public static string Transformer_infoTextPart {
            get {
                return ResourceManager.GetString("Transformer_infoTextPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string TW_deleteButtonContent {
            get {
                return ResourceManager.GetString("TW_deleteButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difficulty:.
        /// </summary>
        public static string TW_difficultyComboboxTitle {
            get {
                return ResourceManager.GetString("TW_difficultyComboboxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy.
        /// </summary>
        public static string TW_difficultyEasyComboboxItem {
            get {
                return ResourceManager.GetString("TW_difficultyEasyComboboxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard.
        /// </summary>
        public static string TW_difficultyHardComboboxItem {
            get {
                return ResourceManager.GetString("TW_difficultyHardComboboxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string TW_difficultyMediumComboboxItem {
            get {
                return ResourceManager.GetString("TW_difficultyMediumComboboxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warmup.
        /// </summary>
        public static string TW_difficultyWarmupComboboxItem {
            get {
                return ResourceManager.GetString("TW_difficultyWarmupComboboxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, add at least one exercise to this training.
        /// </summary>
        public static string TW_emptyTrainingListErrorMessage {
            get {
                return ResourceManager.GetString("TW_emptyTrainingListErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training is empty.
        /// </summary>
        public static string TW_emptyTrainingListErrorTitle {
            get {
                return ResourceManager.GetString("TW_emptyTrainingListErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! Data of this training was moved or permanently corrupted. You&apos;ll be redirected to main menu.
        /// </summary>
        public static string TW_emptyTrainingObjectErrorMessage {
            get {
                return ResourceManager.GetString("TW_emptyTrainingObjectErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading training data error.
        /// </summary>
        public static string TW_emptyTrainingObjectErrorTitle {
            get {
                return ResourceManager.GetString("TW_emptyTrainingObjectErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter a number where expected.
        /// </summary>
        public static string TW_enterNumberErrorMessage {
            get {
                return ResourceManager.GetString("TW_enterNumberErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete an exercise called.
        /// </summary>
        public static string TW_exerciseDeletionPromptMessage {
            get {
                return ResourceManager.GetString("TW_exerciseDeletionPromptMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation of deletion.
        /// </summary>
        public static string TW_exerciseDeletionPromptTitle {
            get {
                return ResourceManager.GetString("TW_exerciseDeletionPromptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark as completed.
        /// </summary>
        public static string TW_markAsCompletedButtonContent {
            get {
                return ResourceManager.GetString("TW_markAsCompletedButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new exercise.
        /// </summary>
        public static string TW_newExerciseButtonContent {
            get {
                return ResourceManager.GetString("TW_newExerciseButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no exercises yet. Add one to fill this training up.
        /// </summary>
        public static string TW_noExercisesTextBlock {
            get {
                return ResourceManager.GetString("TW_noExercisesTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and back to main menu.
        /// </summary>
        public static string TW_saveAndBackToMainButtonContent {
            get {
                return ResourceManager.GetString("TW_saveAndBackToMainButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets count:.
        /// </summary>
        public static string TW_setsCountTextBlock {
            get {
                return ResourceManager.GetString("TW_setsCountTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total exercises:.
        /// </summary>
        public static string TW_totalExercisesText {
            get {
                return ResourceManager.GetString("TW_totalExercisesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . Total sets:.
        /// </summary>
        public static string TW_totalSetsText {
            get {
                return ResourceManager.GetString("TW_totalSetsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training with such title already exists. Please, change the title of this training.
        /// </summary>
        public static string TW_trainingAlreadyExistsErrorMessage {
            get {
                return ResourceManager.GetString("TW_trainingAlreadyExistsErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Such training already exists.
        /// </summary>
        public static string TW_trainingAlreadyExistsErrorTitle {
            get {
                return ResourceManager.GetString("TW_trainingAlreadyExistsErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete this training?.
        /// </summary>
        public static string TW_trainingDeletionPromptMessage {
            get {
                return ResourceManager.GetString("TW_trainingDeletionPromptMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation of deletion.
        /// </summary>
        public static string TW_trainingDeletionPromptTitle {
            get {
                return ResourceManager.GetString("TW_trainingDeletionPromptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new name of training. Whitespaces are not an option.
        /// </summary>
        public static string TW_trainingTitleErrorMessage {
            get {
                return ResourceManager.GetString("TW_trainingTitleErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error occured while trying to save the data. Please, try again.
        /// </summary>
        public static string TW_unknownSavingErrorMessage {
            get {
                return ResourceManager.GetString("TW_unknownSavingErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving error.
        /// </summary>
        public static string TW_unknownSavingErrorTitle {
            get {
                return ResourceManager.GetString("TW_unknownSavingErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training.
        /// </summary>
        public static string TW_windowTitle {
            get {
                return ResourceManager.GetString("TW_windowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong input.
        /// </summary>
        public static string wrongInputTitle {
            get {
                return ResourceManager.GetString("wrongInputTitle", resourceCulture);
            }
        }
    }
}
