//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymTrack.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LiteratureUkrainian {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LiteratureUkrainian() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GymTrack.Resources.Languages.LiteratureUkrainian", typeof(LiteratureUkrainian).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12 год.
        /// </summary>
        public static string AppSW_12formatComboboxItem {
            get {
                return ResourceManager.GetString("AppSW_12formatComboboxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12-годинний формат: формат з AM/PM.
        /// </summary>
        public static string AppSW_12formatDescription {
            get {
                return ResourceManager.GetString("AppSW_12formatDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24 год.
        /// </summary>
        public static string AppSW_24formatComboboxItem {
            get {
                return ResourceManager.GetString("AppSW_24formatComboboxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24-годинний формат: формат без AM чи PM.
        /// </summary>
        public static string AppSW_24formatDescription {
            get {
                return ResourceManager.GetString("AppSW_24formatDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Барбі.
        /// </summary>
        public static string AppSW_barbieThemeComboboxItem {
            get {
                return ResourceManager.GetString("AppSW_barbieThemeComboboxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кожна ніч - дівчача ніч.
        /// </summary>
        public static string AppSW_barbieThemeDescription {
            get {
                return ResourceManager.GetString("AppSW_barbieThemeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поточний шлях:.
        /// </summary>
        public static string AppSW_currentTrainingsFolderText {
            get {
                return ResourceManager.GetString("AppSW_currentTrainingsFolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Темна.
        /// </summary>
        public static string AppSW_darkThemeComboboxItem {
            get {
                return ResourceManager.GetString("AppSW_darkThemeComboboxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Темний фон, світлий передній план. Для поціновувачів темних тем.
        /// </summary>
        public static string AppSW_darkThemeDescription {
            get {
                return ResourceManager.GetString("AppSW_darkThemeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Англійська.
        /// </summary>
        public static string AppSW_engLanguageComboboxItem {
            get {
                return ResourceManager.GetString("AppSW_engLanguageComboboxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Класична англійська мова.
        /// </summary>
        public static string AppSW_engLanguageDescription {
            get {
                return ResourceManager.GetString("AppSW_engLanguageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Експорт налаштувань програми.
        /// </summary>
        public static string AppSW_exportAppSettingsButtonContent {
            get {
                return ResourceManager.GetString("AppSW_exportAppSettingsButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Експортуйте ваші налаштування програми:.
        /// </summary>
        public static string AppSW_exportSettingsTextBlock {
            get {
                return ResourceManager.GetString("AppSW_exportSettingsTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обрати нову папку.
        /// </summary>
        public static string AppSW_folderButtonContent {
            get {
                return ResourceManager.GetString("AppSW_folderButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хакер.
        /// </summary>
        public static string AppSW_hackerThemeComboboxItem {
            get {
                return ResourceManager.GetString("AppSW_hackerThemeComboboxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Темний фон, переважно зелений передній план. Для поціновувачів хакерських стереотипів.
        /// </summary>
        public static string AppSW_hackerThemeDescription {
            get {
                return ResourceManager.GetString("AppSW_hackerThemeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конфігуруйте GymTrack як завгодно!.
        /// </summary>
        public static string AppSW_header {
            get {
                return ResourceManager.GetString("AppSW_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Імпорт налаштувань програми.
        /// </summary>
        public static string AppSW_importAppSettingsButtonContent {
            get {
                return ResourceManager.GetString("AppSW_importAppSettingsButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оберіть файл конфігурації застосунку:.
        /// </summary>
        public static string AppSW_importSettingsTextBlock {
            get {
                return ResourceManager.GetString("AppSW_importSettingsTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мова:.
        /// </summary>
        public static string AppSW_languageTextBlock {
            get {
                return ResourceManager.GetString("AppSW_languageTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Світла.
        /// </summary>
        public static string AppSW_lightThemeComboboxItem {
            get {
                return ResourceManager.GetString("AppSW_lightThemeComboboxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Світлий фон, темний передній план. Для поціновувачів світлих тем.
        /// </summary>
        public static string AppSW_lightThemeDescription {
            get {
                return ResourceManager.GetString("AppSW_lightThemeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Літературна українська.
        /// </summary>
        public static string AppSW_literatureUkrLanguageComboboxItem {
            get {
                return ResourceManager.GetString("AppSW_literatureUkrLanguageComboboxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чиста українська мова.
        /// </summary>
        public static string AppSW_literatureUkrLanguageDescription {
            get {
                return ResourceManager.GetString("AppSW_literatureUkrLanguageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оппенгеймер.
        /// </summary>
        public static string AppSW_oppenheimerThemeComboboxItem {
            get {
                return ResourceManager.GetString("AppSW_oppenheimerThemeComboboxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Я став смертю, руйнівником світів.
        /// </summary>
        public static string AppSW_oppenheimerThemeDescription {
            get {
                return ResourceManager.GetString("AppSW_oppenheimerThemeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Розмовна українська.
        /// </summary>
        public static string AppSW_spokenUkrLanguageComboboxItem {
            get {
                return ResourceManager.GetString("AppSW_spokenUkrLanguageComboboxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файна мова з підколами.
        /// </summary>
        public static string AppSW_spokenUkrLanguageDescription {
            get {
                return ResourceManager.GetString("AppSW_spokenUkrLanguageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тема:.
        /// </summary>
        public static string AppSW_themeTextBlock {
            get {
                return ResourceManager.GetString("AppSW_themeTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Формат часу:.
        /// </summary>
        public static string AppSW_timeFormatTextBlock {
            get {
                return ResourceManager.GetString("AppSW_timeFormatTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шлях до папки з даними тренувань:.
        /// </summary>
        public static string AppSW_trainingFolderPathTextBlock {
            get {
                return ResourceManager.GetString("AppSW_trainingFolderPathTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Налаштування застосунку.
        /// </summary>
        public static string AppSW_windowTitle {
            get {
                return ResourceManager.GetString("AppSW_windowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to П&apos;ят.
        /// </summary>
        public static string ASW_dayoffsFriday {
            get {
                return ResourceManager.GetString("ASW_dayoffsFriday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ви будете відпочивати в такі дні:.
        /// </summary>
        public static string ASW_dayoffsInfoTextBlock {
            get {
                return ResourceManager.GetString("ASW_dayoffsInfoTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вам потрібно буде тренуватись щодня.
        /// </summary>
        public static string ASW_dayoffsInfoTextBlockDefault {
            get {
                return ResourceManager.GetString("ASW_dayoffsInfoTextBlockDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пон.
        /// </summary>
        public static string ASW_dayoffsMonday {
            get {
                return ResourceManager.GetString("ASW_dayoffsMonday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Суб.
        /// </summary>
        public static string ASW_dayoffsSaturday {
            get {
                return ResourceManager.GetString("ASW_dayoffsSaturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нед.
        /// </summary>
        public static string ASW_dayoffsSunday {
            get {
                return ResourceManager.GetString("ASW_dayoffsSunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вільні від тренувань дні:.
        /// </summary>
        public static string ASW_dayoffsTextBlock {
            get {
                return ResourceManager.GetString("ASW_dayoffsTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чет.
        /// </summary>
        public static string ASW_dayoffsThursday {
            get {
                return ResourceManager.GetString("ASW_dayoffsThursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вів.
        /// </summary>
        public static string ASW_dayoffsTuesday {
            get {
                return ResourceManager.GetString("ASW_dayoffsTuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сер.
        /// </summary>
        public static string ASW_dayoffsWednesday {
            get {
                return ResourceManager.GetString("ASW_dayoffsWednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Експорт налаштувань користувача.
        /// </summary>
        public static string ASW_exportAccountButtonContent {
            get {
                return ResourceManager.GetString("ASW_exportAccountButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Експортуйте ваші користувацькі налаштування:.
        /// </summary>
        public static string ASW_exportAccountTextBlock {
            get {
                return ResourceManager.GetString("ASW_exportAccountTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to П&apos;ятниця.
        /// </summary>
        public static string ASW_friday {
            get {
                return ResourceManager.GetString("ASW_friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш обліковий запис.
        /// </summary>
        public static string ASW_header {
            get {
                return ResourceManager.GetString("ASW_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Створіть обліковий запис чи імпортуйте існуючий!.
        /// </summary>
        public static string ASW_headerNoAccount {
            get {
                return ResourceManager.GetString("ASW_headerNoAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Імпорт існуючого запису.
        /// </summary>
        public static string ASW_importAccountButtonContent {
            get {
                return ResourceManager.GetString("ASW_importAccountButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оберіть файл конфігурації облікового запису:.
        /// </summary>
        public static string ASW_importAccountTextBlock {
            get {
                return ResourceManager.GetString("ASW_importAccountTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Понеділок.
        /// </summary>
        public static string ASW_monday {
            get {
                return ResourceManager.GetString("ASW_monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Будь ласка, введіть ваше ім&apos;я.
        /// </summary>
        public static string ASW_nameEntryError {
            get {
                return ResourceManager.GetString("ASW_nameEntryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ім&apos;я:.
        /// </summary>
        public static string ASW_nameTextBlock {
            get {
                return ResourceManager.GetString("ASW_nameTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть ваше ім&apos;я тут.
        /// </summary>
        public static string ASW_nameTextBox {
            get {
                return ResourceManager.GetString("ASW_nameTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Субота.
        /// </summary>
        public static string ASW_saturday {
            get {
                return ResourceManager.GetString("ASW_saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неділя.
        /// </summary>
        public static string ASW_sunday {
            get {
                return ResourceManager.GetString("ASW_sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Четвер.
        /// </summary>
        public static string ASW_thursday {
            get {
                return ResourceManager.GetString("ASW_thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вівторок.
        /// </summary>
        public static string ASW_tuesday {
            get {
                return ResourceManager.GetString("ASW_tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Середа.
        /// </summary>
        public static string ASW_wednesday {
            get {
                return ResourceManager.GetString("ASW_wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Будь ласка, введіть вашу вагу належним чином.
        /// </summary>
        public static string ASW_weightEntryError {
            get {
                return ResourceManager.GetString("ASW_weightEntryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вага:.
        /// </summary>
        public static string ASW_weightTextBlock {
            get {
                return ResourceManager.GetString("ASW_weightTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть вашу вагу тут (необов&apos;язково).
        /// </summary>
        public static string ASW_weightTextBoxDefault {
            get {
                return ResourceManager.GetString("ASW_weightTextBoxDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відслідковувати вагу.
        /// </summary>
        public static string ASW_weightTrackTextBlock {
            get {
                return ResourceManager.GetString("ASW_weightTrackTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Налаштування облікового запису.
        /// </summary>
        public static string ASW_windowTitle {
            get {
                return ResourceManager.GetString("ASW_windowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редагувати.
        /// </summary>
        public static string editButtonEditModeContent {
            get {
                return ResourceManager.GetString("editButtonEditModeContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зберегти.
        /// </summary>
        public static string editButtonSaveModeContent {
            get {
                return ResourceManager.GetString("editButtonSaveModeContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бажана властивість(повтори/секунди тощо).
        /// </summary>
        public static string ExerciseDto_customPropertyPrompt {
            get {
                return ResourceManager.GetString("ExerciseDto_customPropertyPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опис вправи.
        /// </summary>
        public static string ExerciseDto_descriptionPrompt {
            get {
                return ResourceManager.GetString("ExerciseDto_descriptionPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назва вправи.
        /// </summary>
        public static string ExerciseDto_titlePrompt {
            get {
                return ResourceManager.GetString("ExerciseDto_titlePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кількість підходів:.
        /// </summary>
        public static string exerciseMainInfoSetsText {
            get {
                return ResourceManager.GetString("exerciseMainInfoSetsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Будь ласка, заповність всі потрібні поля.
        /// </summary>
        public static string fillFieldsErrorMessage {
            get {
                return ResourceManager.GetString("fillFieldsErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необхідно надати дані.
        /// </summary>
        public static string fillFieldsErrorTitle {
            get {
                return ResourceManager.GetString("fillFieldsErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл JSON.
        /// </summary>
        public static string jsonFileTitle {
            get {
                return ResourceManager.GetString("jsonFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад до меню.
        /// </summary>
        public static string mainMenuButtonContent {
            get {
                return ResourceManager.GetString("mainMenuButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обліковий запис.
        /// </summary>
        public static string MW_accountButtonContent {
            get {
                return ResourceManager.GetString("MW_accountButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аналітика.
        /// </summary>
        public static string MW_analyticsButtonContent {
            get {
                return ResourceManager.GetString("MW_analyticsButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ви справді хочете вийти із застосунку?.
        /// </summary>
        public static string MW_exitConfirmationText {
            get {
                return ResourceManager.GetString("MW_exitConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вихід із застосунку.
        /// </summary>
        public static string MW_exitConfirmationTitle {
            get {
                return ResourceManager.GetString("MW_exitConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Жодної програми тренування не було додано. Додайте тренування та розпочніть свій шлях у спорті!.
        /// </summary>
        public static string MW_noTrainingsText {
            get {
                return ResourceManager.GetString("MW_noTrainingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відкрити.
        /// </summary>
        public static string MW_openTrainingButtonContent {
            get {
                return ResourceManager.GetString("MW_openTrainingButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Налаштування.
        /// </summary>
        public static string MW_settingsButtonContent {
            get {
                return ResourceManager.GetString("MW_settingsButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додати трен..
        /// </summary>
        public static string MW_trainingButtonContent {
            get {
                return ResourceManager.GetString("MW_trainingButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вітаємо, .
        /// </summary>
        public static string MW_welcomeText {
            get {
                return ResourceManager.GetString("MW_welcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Головне меню.
        /// </summary>
        public static string MW_windowTitle {
            get {
                return ResourceManager.GetString("MW_windowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Будь ласка, збережіть всі дані, що ви зараз редагуєте.
        /// </summary>
        public static string saveDataErrorMessage {
            get {
                return ResourceManager.GetString("saveDataErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необхідно зберегти дані.
        /// </summary>
        public static string saveDataErrorTitle {
            get {
                return ResourceManager.GetString("saveDataErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Налаштування не було експортовано. Будь ласка, спробуйте ще раз.
        /// </summary>
        public static string settingsExportErrorMessage {
            get {
                return ResourceManager.GetString("settingsExportErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помилка експорту налаштувань.
        /// </summary>
        public static string settingsExportErrorTitle {
            get {
                return ResourceManager.GetString("settingsExportErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не вийшло зчитати інформацію із наданого файлу.
        /// </summary>
        public static string settingsImportErrorMessage {
            get {
                return ResourceManager.GetString("settingsImportErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неправильний чи пошкоджений файл конфігурації.
        /// </summary>
        public static string settingsImportErrorTitle {
            get {
                return ResourceManager.GetString("settingsImportErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Всі дані є вашими. Вони зберігаються тільки локально на вашому пристрої.
        /// </summary>
        public static string settingsSubHeader {
            get {
                return ResourceManager.GetString("settingsSubHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Налаштування успішно експортовано.
        /// </summary>
        public static string successfullSettingsExportMessage {
            get {
                return ResourceManager.GetString("successfullSettingsExportMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Експорт успішний.
        /// </summary>
        public static string successfullSettingsExportTitle {
            get {
                return ResourceManager.GetString("successfullSettingsExportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Налаштування успішно імпортовано.
        /// </summary>
        public static string successfullSettingsImportMessage {
            get {
                return ResourceManager.GetString("successfullSettingsImportMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Імпорт успішний.
        /// </summary>
        public static string successfullSettingsImportTitle {
            get {
                return ResourceManager.GetString("successfullSettingsImportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скасувати.
        /// </summary>
        public static string TCompW_cancelButtonContent {
            get {
                return ResourceManager.GetString("TCompW_cancelButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Підтвердити.
        /// </summary>
        public static string TCompW_confirmButtonContent {
            get {
                return ResourceManager.GetString("TCompW_confirmButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Позначення тренування виконаним.
        /// </summary>
        public static string TCompW_windowTitle {
            get {
                return ResourceManager.GetString("TCompW_windowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть назву тренування тут.
        /// </summary>
        public static string TrainingDto_trainingTitlePrompt {
            get {
                return ResourceManager.GetString("TrainingDto_trainingTitlePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to хвилина.
        /// </summary>
        public static string Transformer_infoTextMinute {
            get {
                return ResourceManager.GetString("Transformer_infoTextMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to хвилин(и).
        /// </summary>
        public static string Transformer_infoTextMinutes {
            get {
                return ResourceManager.GetString("Transformer_infoTextMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to вправ(и) загалом, приблизний час відпочинку:.
        /// </summary>
        public static string Transformer_infoTextPart {
            get {
                return ResourceManager.GetString("Transformer_infoTextPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видалити.
        /// </summary>
        public static string TW_deleteButtonContent {
            get {
                return ResourceManager.GetString("TW_deleteButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Складність:.
        /// </summary>
        public static string TW_difficultyComboboxTitle {
            get {
                return ResourceManager.GetString("TW_difficultyComboboxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Легко.
        /// </summary>
        public static string TW_difficultyEasyComboboxItem {
            get {
                return ResourceManager.GetString("TW_difficultyEasyComboboxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Важко.
        /// </summary>
        public static string TW_difficultyHardComboboxItem {
            get {
                return ResourceManager.GetString("TW_difficultyHardComboboxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Середньо.
        /// </summary>
        public static string TW_difficultyMediumComboboxItem {
            get {
                return ResourceManager.GetString("TW_difficultyMediumComboboxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Розминка.
        /// </summary>
        public static string TW_difficultyWarmupComboboxItem {
            get {
                return ResourceManager.GetString("TW_difficultyWarmupComboboxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Будь ласка, додайте хоча б одну вправу до тренування.
        /// </summary>
        public static string TW_emptyTrainingListErrorMessage {
            get {
                return ResourceManager.GetString("TW_emptyTrainingListErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тренування порожнє.
        /// </summary>
        public static string TW_emptyTrainingListErrorTitle {
            get {
                return ResourceManager.GetString("TW_emptyTrainingListErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отакої! Дані цього тренування було переміщено чи безповоротньо пошкоджено. Вас буде перенаправлено до головного меню.
        /// </summary>
        public static string TW_emptyTrainingObjectErrorMessage {
            get {
                return ResourceManager.GetString("TW_emptyTrainingObjectErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помилка читки даних.
        /// </summary>
        public static string TW_emptyTrainingObjectErrorTitle {
            get {
                return ResourceManager.GetString("TW_emptyTrainingObjectErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Будь ласка, введіть число, де це потрібно.
        /// </summary>
        public static string TW_enterNumberErrorMessage {
            get {
                return ResourceManager.GetString("TW_enterNumberErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чи справді ви хочете видалити вправу під назвою.
        /// </summary>
        public static string TW_exerciseDeletionPromptMessage {
            get {
                return ResourceManager.GetString("TW_exerciseDeletionPromptMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Підтвердження видалення.
        /// </summary>
        public static string TW_exerciseDeletionPromptTitle {
            get {
                return ResourceManager.GetString("TW_exerciseDeletionPromptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Позначити виконаним.
        /// </summary>
        public static string TW_markAsCompletedButtonContent {
            get {
                return ResourceManager.GetString("TW_markAsCompletedButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додати нову вправу.
        /// </summary>
        public static string TW_newExerciseButtonContent {
            get {
                return ResourceManager.GetString("TW_newExerciseButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тут поки що немає вправ. Додайте нову вправу, щоб наповнити це тренування.
        /// </summary>
        public static string TW_noExercisesTextBlock {
            get {
                return ResourceManager.GetString("TW_noExercisesTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зберегти та назад до меню.
        /// </summary>
        public static string TW_saveAndBackToMainButtonContent {
            get {
                return ResourceManager.GetString("TW_saveAndBackToMainButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кількість підходів:.
        /// </summary>
        public static string TW_setsCountTextBlock {
            get {
                return ResourceManager.GetString("TW_setsCountTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загалом вправ:.
        /// </summary>
        public static string TW_totalExercisesText {
            get {
                return ResourceManager.GetString("TW_totalExercisesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . Загалом підходів:.
        /// </summary>
        public static string TW_totalSetsText {
            get {
                return ResourceManager.GetString("TW_totalSetsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тренування з такою назвою вже існує. Будь ласка, змініть назву цього тренування.
        /// </summary>
        public static string TW_trainingAlreadyExistsErrorMessage {
            get {
                return ResourceManager.GetString("TW_trainingAlreadyExistsErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Таке тренування вже існує.
        /// </summary>
        public static string TW_trainingAlreadyExistsErrorTitle {
            get {
                return ResourceManager.GetString("TW_trainingAlreadyExistsErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чи справді ви хочете видалити це тренування?.
        /// </summary>
        public static string TW_trainingDeletionPromptMessage {
            get {
                return ResourceManager.GetString("TW_trainingDeletionPromptMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Підтвердження видалення.
        /// </summary>
        public static string TW_trainingDeletionPromptTitle {
            get {
                return ResourceManager.GetString("TW_trainingDeletionPromptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть нову назву тренування. Пробілами називати не дозволено.
        /// </summary>
        public static string TW_trainingTitleErrorMessage {
            get {
                return ResourceManager.GetString("TW_trainingTitleErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невідома помилка виникла при спробі запису даних. Будь ласка, спробуйте ще раз.
        /// </summary>
        public static string TW_unknownSavingErrorMessage {
            get {
                return ResourceManager.GetString("TW_unknownSavingErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помилка зберігання.
        /// </summary>
        public static string TW_unknownSavingErrorTitle {
            get {
                return ResourceManager.GetString("TW_unknownSavingErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тренування.
        /// </summary>
        public static string TW_windowTitle {
            get {
                return ResourceManager.GetString("TW_windowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неправильний ввід.
        /// </summary>
        public static string wrongInputTitle {
            get {
                return ResourceManager.GetString("wrongInputTitle", resourceCulture);
            }
        }
    }
}
