//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymTrack.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SpokenUkrainian {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SpokenUkrainian() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GymTrack.Resources.Languages.SpokenUkrainian", typeof(SpokenUkrainian).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12 годинки.
        /// </summary>
        public static string AppSW_12formatComboboxItem {
            get {
                return ResourceManager.GetString("AppSW_12formatComboboxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12-годинний формат: формат з модними AM/PM.
        /// </summary>
        public static string AppSW_12formatDescription {
            get {
                return ResourceManager.GetString("AppSW_12formatDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24 годинки.
        /// </summary>
        public static string AppSW_24formatComboboxItem {
            get {
                return ResourceManager.GetString("AppSW_24formatComboboxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24-годинний формат: нормальний формат, без цих ваших AM чи PM.
        /// </summary>
        public static string AppSW_24formatDescription {
            get {
                return ResourceManager.GetString("AppSW_24formatDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Барбі.
        /// </summary>
        public static string AppSW_barbieThemeComboboxItem {
            get {
                return ResourceManager.GetString("AppSW_barbieThemeComboboxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кожна ніч - дівоча ніч.
        /// </summary>
        public static string AppSW_barbieThemeDescription {
            get {
                return ResourceManager.GetString("AppSW_barbieThemeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ось де папка:.
        /// </summary>
        public static string AppSW_currentTrainingsFolderText {
            get {
                return ResourceManager.GetString("AppSW_currentTrainingsFolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Темна.
        /// </summary>
        public static string AppSW_darkThemeComboboxItem {
            get {
                return ResourceManager.GetString("AppSW_darkThemeComboboxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Темний фон, світлий перед. Для поціновувачів погіршення зору у віці 30+.
        /// </summary>
        public static string AppSW_darkThemeDescription {
            get {
                return ResourceManager.GetString("AppSW_darkThemeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Енглісх.
        /// </summary>
        public static string AppSW_engLanguageComboboxItem {
            get {
                return ResourceManager.GetString("AppSW_engLanguageComboboxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нудна англійська мова.
        /// </summary>
        public static string AppSW_engLanguageDescription {
            get {
                return ResourceManager.GetString("AppSW_engLanguageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Експорт цих налаштувань.
        /// </summary>
        public static string AppSW_exportAppSettingsButtonContent {
            get {
                return ResourceManager.GetString("AppSW_exportAppSettingsButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Експортуй налаштування програми:.
        /// </summary>
        public static string AppSW_exportSettingsTextBlock {
            get {
                return ResourceManager.GetString("AppSW_exportSettingsTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хочу нову папку.
        /// </summary>
        public static string AppSW_folderButtonContent {
            get {
                return ResourceManager.GetString("AppSW_folderButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мамин хацкер.
        /// </summary>
        public static string AppSW_hackerThemeComboboxItem {
            get {
                return ResourceManager.GetString("AppSW_hackerThemeComboboxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Темний фон, переважно зелений перед. Для маминих хацкерів.
        /// </summary>
        public static string AppSW_hackerThemeDescription {
            get {
                return ResourceManager.GetString("AppSW_hackerThemeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чуєш, та конфігуруй цей GymTrack як заманеться!.
        /// </summary>
        public static string AppSW_header {
            get {
                return ResourceManager.GetString("AppSW_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Імпорт моїх налаштувань.
        /// </summary>
        public static string AppSW_importAppSettingsButtonContent {
            get {
                return ResourceManager.GetString("AppSW_importAppSettingsButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обери шлях, де треба взяти конфігурацію застосунку:.
        /// </summary>
        public static string AppSW_importSettingsTextBlock {
            get {
                return ResourceManager.GetString("AppSW_importSettingsTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мова:.
        /// </summary>
        public static string AppSW_languageTextBlock {
            get {
                return ResourceManager.GetString("AppSW_languageTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Світла.
        /// </summary>
        public static string AppSW_lightThemeComboboxItem {
            get {
                return ResourceManager.GetString("AppSW_lightThemeComboboxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Світлий фон, темний перед. Для поціновувачів яскравого світла.
        /// </summary>
        public static string AppSW_lightThemeDescription {
            get {
                return ResourceManager.GetString("AppSW_lightThemeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Літературна українська.
        /// </summary>
        public static string AppSW_literatureUkrLanguageComboboxItem {
            get {
                return ResourceManager.GetString("AppSW_literatureUkrLanguageComboboxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чиста українська мова.
        /// </summary>
        public static string AppSW_literatureUkrLanguageDescription {
            get {
                return ResourceManager.GetString("AppSW_literatureUkrLanguageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оппенгеймер.
        /// </summary>
        public static string AppSW_oppenheimerThemeComboboxItem {
            get {
                return ResourceManager.GetString("AppSW_oppenheimerThemeComboboxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Я став смертю, руйнівником світів.
        /// </summary>
        public static string AppSW_oppenheimerThemeDescription {
            get {
                return ResourceManager.GetString("AppSW_oppenheimerThemeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Розмовна українська.
        /// </summary>
        public static string AppSW_spokenUkrLanguageComboboxItem {
            get {
                return ResourceManager.GetString("AppSW_spokenUkrLanguageComboboxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файна мова з підколами.
        /// </summary>
        public static string AppSW_spokenUkrLanguageDescription {
            get {
                return ResourceManager.GetString("AppSW_spokenUkrLanguageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тема:.
        /// </summary>
        public static string AppSW_themeTextBlock {
            get {
                return ResourceManager.GetString("AppSW_themeTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Формат часу:.
        /// </summary>
        public static string AppSW_timeFormatTextBlock {
            get {
                return ResourceManager.GetString("AppSW_timeFormatTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шлях до папки з даними твоїх вельми, трясця, чудових тренувань:.
        /// </summary>
        public static string AppSW_trainingFolderPathTextBlock {
            get {
                return ResourceManager.GetString("AppSW_trainingFolderPathTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Налаштування застосунку.
        /// </summary>
        public static string AppSW_windowTitle {
            get {
                return ResourceManager.GetString("AppSW_windowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to П&apos;ят.
        /// </summary>
        public static string ASW_dayoffsFriday {
            get {
                return ResourceManager.GetString("ASW_dayoffsFriday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поваляєшся в такі дні:.
        /// </summary>
        public static string ASW_dayoffsInfoTextBlock {
            get {
                return ResourceManager.GetString("ASW_dayoffsInfoTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чудово! Будеш тренуватись щодня!.
        /// </summary>
        public static string ASW_dayoffsInfoTextBlockDefault {
            get {
                return ResourceManager.GetString("ASW_dayoffsInfoTextBlockDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зроз.
        /// </summary>
        public static string ASW_dayoffsMonday {
            get {
                return ResourceManager.GetString("ASW_dayoffsMonday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Під.
        /// </summary>
        public static string ASW_dayoffsSaturday {
            get {
                return ResourceManager.GetString("ASW_dayoffsSaturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нід.
        /// </summary>
        public static string ASW_dayoffsSunday {
            get {
                return ResourceManager.GetString("ASW_dayoffsSunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дні лежання на дивані:.
        /// </summary>
        public static string ASW_dayoffsTextBlock {
            get {
                return ResourceManager.GetString("ASW_dayoffsTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Щот.
        /// </summary>
        public static string ASW_dayoffsThursday {
            get {
                return ResourceManager.GetString("ASW_dayoffsThursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вів.
        /// </summary>
        public static string ASW_dayoffsTuesday {
            get {
                return ResourceManager.GetString("ASW_dayoffsTuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сер.
        /// </summary>
        public static string ASW_dayoffsWednesday {
            get {
                return ResourceManager.GetString("ASW_dayoffsWednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Експорт цих даних.
        /// </summary>
        public static string ASW_exportAccountButtonContent {
            get {
                return ResourceManager.GetString("ASW_exportAccountButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Експортуй дані про себе:.
        /// </summary>
        public static string ASW_exportAccountTextBlock {
            get {
                return ResourceManager.GetString("ASW_exportAccountTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to П&apos;ятниця.
        /// </summary>
        public static string ASW_friday {
            get {
                return ResourceManager.GetString("ASW_friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всі твої дані.
        /// </summary>
        public static string ASW_header {
            get {
                return ResourceManager.GetString("ASW_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Створіть обліковий запис чи імпортуй той, що вже є!.
        /// </summary>
        public static string ASW_headerNoAccount {
            get {
                return ResourceManager.GetString("ASW_headerNoAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Імпорт існуючих даних про тебе.
        /// </summary>
        public static string ASW_importAccountButtonContent {
            get {
                return ResourceManager.GetString("ASW_importAccountButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обери звідки мені читати дані облікового запису:.
        /// </summary>
        public static string ASW_importAccountTextBlock {
            get {
                return ResourceManager.GetString("ASW_importAccountTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зрозеділок.
        /// </summary>
        public static string ASW_monday {
            get {
                return ResourceManager.GetString("ASW_monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чорт забирай! Введи своє ім&apos;я!.
        /// </summary>
        public static string ASW_nameEntryError {
            get {
                return ResourceManager.GetString("ASW_nameEntryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ім&apos;я:.
        /// </summary>
        public static string ASW_nameTextBlock {
            get {
                return ResourceManager.GetString("ASW_nameTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тут вводь своє ім&apos;я.
        /// </summary>
        public static string ASW_nameTextBox {
            get {
                return ResourceManager.GetString("ASW_nameTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Підота.
        /// </summary>
        public static string ASW_saturday {
            get {
                return ResourceManager.GetString("ASW_saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ніділя.
        /// </summary>
        public static string ASW_sunday {
            get {
                return ResourceManager.GetString("ASW_sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Щотвер.
        /// </summary>
        public static string ASW_thursday {
            get {
                return ResourceManager.GetString("ASW_thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вівперунок.
        /// </summary>
        public static string ASW_tuesday {
            get {
                return ResourceManager.GetString("ASW_tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Середа.
        /// </summary>
        public static string ASW_wednesday {
            get {
                return ResourceManager.GetString("ASW_wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стри те, що написано в якості ваги і вкажи її нормально.
        /// </summary>
        public static string ASW_weightEntryError {
            get {
                return ResourceManager.GetString("ASW_weightEntryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вага:.
        /// </summary>
        public static string ASW_weightTextBlock {
            get {
                return ResourceManager.GetString("ASW_weightTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Якщо хочеш, вводь тут вагу.
        /// </summary>
        public static string ASW_weightTextBoxDefault {
            get {
                return ResourceManager.GetString("ASW_weightTextBoxDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хочу знати, що з вагою.
        /// </summary>
        public static string ASW_weightTrackTextBlock {
            get {
                return ResourceManager.GetString("ASW_weightTrackTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Налаштування всього, що стосується тебе.
        /// </summary>
        public static string ASW_windowTitle {
            get {
                return ResourceManager.GetString("ASW_windowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поправити.
        /// </summary>
        public static string editButtonEditModeContent {
            get {
                return ResourceManager.GetString("editButtonEditModeContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запам&apos;ятати.
        /// </summary>
        public static string editButtonSaveModeContent {
            get {
                return ResourceManager.GetString("editButtonSaveModeContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Якась властивість(повтори/секунди чи що).
        /// </summary>
        public static string ExerciseDto_customPropertyPrompt {
            get {
                return ResourceManager.GetString("ExerciseDto_customPropertyPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Що це за вправа.
        /// </summary>
        public static string ExerciseDto_descriptionPrompt {
            get {
                return ResourceManager.GetString("ExerciseDto_descriptionPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назва вправи.
        /// </summary>
        public static string ExerciseDto_titlePrompt {
            get {
                return ResourceManager.GetString("ExerciseDto_titlePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кількість підходів:.
        /// </summary>
        public static string exerciseMainInfoSetsText {
            get {
                return ResourceManager.GetString("exerciseMainInfoSetsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ану заповни всі поля, що треба.
        /// </summary>
        public static string fillFieldsErrorMessage {
            get {
                return ResourceManager.GetString("fillFieldsErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Негайно надай всі потрібні дані.
        /// </summary>
        public static string fillFieldsErrorTitle {
            get {
                return ResourceManager.GetString("fillFieldsErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Джейсон-Мейсон.
        /// </summary>
        public static string jsonFileTitle {
            get {
                return ResourceManager.GetString("jsonFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вйо до меню.
        /// </summary>
        public static string mainMenuButtonContent {
            get {
                return ResourceManager.GetString("mainMenuButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Про тебе.
        /// </summary>
        public static string MW_accountButtonContent {
            get {
                return ResourceManager.GetString("MW_accountButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аналітика.
        /// </summary>
        public static string MW_analyticsButtonContent {
            get {
                return ResourceManager.GetString("MW_analyticsButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тю на тебе! Ти реально хочеш вийти?.
        /// </summary>
        public static string MW_exitConfirmationText {
            get {
                return ResourceManager.GetString("MW_exitConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вихід із застосунку.
        /// </summary>
        public static string MW_exitConfirmationTitle {
            get {
                return ResourceManager.GetString("MW_exitConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Агов, в тебе тут зовсім тренувань немає! Додай хоча б одне і вперед до роботи!.
        /// </summary>
        public static string MW_noTrainingsText {
            get {
                return ResourceManager.GetString("MW_noTrainingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Глянути.
        /// </summary>
        public static string MW_openTrainingButtonContent {
            get {
                return ResourceManager.GetString("MW_openTrainingButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Налаштування.
        /// </summary>
        public static string MW_settingsButtonContent {
            get {
                return ResourceManager.GetString("MW_settingsButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додати ще трен..
        /// </summary>
        public static string MW_trainingButtonContent {
            get {
                return ResourceManager.GetString("MW_trainingButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О, знову ти! Привіт, .
        /// </summary>
        public static string MW_welcomeText {
            get {
                return ResourceManager.GetString("MW_welcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Головне меню.
        /// </summary>
        public static string MW_windowTitle {
            get {
                return ResourceManager.GetString("MW_windowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спочатку може збережеш всі дані, що зараз редагуєш?.
        /// </summary>
        public static string saveDataErrorMessage {
            get {
                return ResourceManager.GetString("saveDataErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Негайно збережи всі дані.
        /// </summary>
        public static string saveDataErrorTitle {
            get {
                return ResourceManager.GetString("saveDataErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Налаштування не було експортовано. Спробуй ще раз, може пощастить.
        /// </summary>
        public static string settingsExportErrorMessage {
            get {
                return ResourceManager.GetString("settingsExportErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ну як так?! Помилка експорту налаштувань.
        /// </summary>
        public static string settingsExportErrorTitle {
            get {
                return ResourceManager.GetString("settingsExportErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Журба... Не вийшло зчитати інформацію із файлу, якого ти мені пхаєш.
        /// </summary>
        public static string settingsImportErrorMessage {
            get {
                return ResourceManager.GetString("settingsImportErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дідько! Неправильний чи пошкоджений файл конфігурації.
        /// </summary>
        public static string settingsImportErrorTitle {
            get {
                return ResourceManager.GetString("settingsImportErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *На жаль, дані я не продаю, так що всі вони є твоїми і зберігаються лише на цьому пристрої.
        /// </summary>
        public static string settingsSubHeader {
            get {
                return ResourceManager.GetString("settingsSubHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Це перемога! Налаштування успішно експортовано.
        /// </summary>
        public static string successfullSettingsExportMessage {
            get {
                return ResourceManager.GetString("successfullSettingsExportMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Експорт виконано.
        /// </summary>
        public static string successfullSettingsExportTitle {
            get {
                return ResourceManager.GetString("successfullSettingsExportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О, так, крихітко! Налаштування успішно імпортовано.
        /// </summary>
        public static string successfullSettingsImportMessage {
            get {
                return ResourceManager.GetString("successfullSettingsImportMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Це чудово! Імпорт успішний.
        /// </summary>
        public static string successfullSettingsImportTitle {
            get {
                return ResourceManager.GetString("successfullSettingsImportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Передумати.
        /// </summary>
        public static string TCompW_cancelButtonContent {
            get {
                return ResourceManager.GetString("TCompW_cancelButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ствердити.
        /// </summary>
        public static string TCompW_confirmButtonContent {
            get {
                return ResourceManager.GetString("TCompW_confirmButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Позначення тренування ледь виконаним.
        /// </summary>
        public static string TCompW_windowTitle {
            get {
                return ResourceManager.GetString("TCompW_windowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Туто вводь назву тренування, ясно?.
        /// </summary>
        public static string TrainingDto_trainingTitlePrompt {
            get {
                return ResourceManager.GetString("TrainingDto_trainingTitlePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to хвилинка.
        /// </summary>
        public static string Transformer_infoTextMinute {
            get {
                return ResourceManager.GetString("Transformer_infoTextMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to хвилинок(ки).
        /// </summary>
        public static string Transformer_infoTextMinutes {
            get {
                return ResourceManager.GetString("Transformer_infoTextMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to вправ(и) загалом, приблизний час відпочинку (ну це явно забагато):.
        /// </summary>
        public static string Transformer_infoTextPart {
            get {
                return ResourceManager.GetString("Transformer_infoTextPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стерти.
        /// </summary>
        public static string TW_deleteButtonContent {
            get {
                return ResourceManager.GetString("TW_deleteButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Складність:.
        /// </summary>
        public static string TW_difficultyComboboxTitle {
            get {
                return ResourceManager.GetString("TW_difficultyComboboxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пф, та легко.
        /// </summary>
        public static string TW_difficultyEasyComboboxItem {
            get {
                return ResourceManager.GetString("TW_difficultyEasyComboboxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неймовірно важко.
        /// </summary>
        public static string TW_difficultyHardComboboxItem {
            get {
                return ResourceManager.GetString("TW_difficultyHardComboboxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ну таке, серединка.
        /// </summary>
        public static string TW_difficultyMediumComboboxItem {
            get {
                return ResourceManager.GetString("TW_difficultyMediumComboboxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Розминочка чисто.
        /// </summary>
        public static string TW_difficultyWarmupComboboxItem {
            get {
                return ResourceManager.GetString("TW_difficultyWarmupComboboxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Смієшся? Та хоча б одну вправу до тренування додай.
        /// </summary>
        public static string TW_emptyTrainingListErrorMessage {
            get {
                return ResourceManager.GetString("TW_emptyTrainingListErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Агов, тренування пусте.
        /// </summary>
        public static string TW_emptyTrainingListErrorTitle {
            get {
                return ResourceManager.GetString("TW_emptyTrainingListErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чорт би його побрав! Дані цього тренування було посунуто чи геть пошкоджено. Зараз перекинемо тебе назад до головного меню.
        /// </summary>
        public static string TW_emptyTrainingObjectErrorMessage {
            get {
                return ResourceManager.GetString("TW_emptyTrainingObjectErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Овва! Помилка читки даних.
        /// </summary>
        public static string TW_emptyTrainingObjectErrorTitle {
            get {
                return ResourceManager.GetString("TW_emptyTrainingObjectErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Що ти туди пхаєш? Там число треба!.
        /// </summary>
        public static string TW_enterNumberErrorMessage {
            get {
                return ResourceManager.GetString("TW_enterNumberErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чи хочеш ти реально видалити вправу під назвою.
        /// </summary>
        public static string TW_exerciseDeletionPromptMessage {
            get {
                return ResourceManager.GetString("TW_exerciseDeletionPromptMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ану підтверди видалення.
        /// </summary>
        public static string TW_exerciseDeletionPromptTitle {
            get {
                return ResourceManager.GetString("TW_exerciseDeletionPromptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Позначити ледь виконаним.
        /// </summary>
        public static string TW_markAsCompletedButtonContent {
            get {
                return ResourceManager.GetString("TW_markAsCompletedButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додати якусь неймовірну вправу.
        /// </summary>
        public static string TW_newExerciseButtonContent {
            get {
                return ResourceManager.GetString("TW_newExerciseButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тут пусто, вправ тупо нуль. Додай нову вправу, щоб хоч якийсь гіпотетичний сенс в цьому тренуванні був.
        /// </summary>
        public static string TW_noExercisesTextBlock {
            get {
                return ResourceManager.GetString("TW_noExercisesTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зберегти та вйо до меню.
        /// </summary>
        public static string TW_saveAndBackToMainButtonContent {
            get {
                return ResourceManager.GetString("TW_saveAndBackToMainButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кількість підходів:.
        /// </summary>
        public static string TW_setsCountTextBlock {
            get {
                return ResourceManager.GetString("TW_setsCountTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всього вправ (тю, як мало):.
        /// </summary>
        public static string TW_totalExercisesText {
            get {
                return ResourceManager.GetString("TW_totalExercisesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . Загалом підходів:.
        /// </summary>
        public static string TW_totalSetsText {
            get {
                return ResourceManager.GetString("TW_totalSetsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тренування з такою назвою вже є. Може зміниш назву, нє?.
        /// </summary>
        public static string TW_trainingAlreadyExistsErrorMessage {
            get {
                return ResourceManager.GetString("TW_trainingAlreadyExistsErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Агов, таке тренування вже є.
        /// </summary>
        public static string TW_trainingAlreadyExistsErrorTitle {
            get {
                return ResourceManager.GetString("TW_trainingAlreadyExistsErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ти реально хочеш видалити це тренування? З якого це чуда?.
        /// </summary>
        public static string TW_trainingDeletionPromptMessage {
            get {
                return ResourceManager.GetString("TW_trainingDeletionPromptMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ану підтверди видалення.
        /// </summary>
        public static string TW_trainingDeletionPromptTitle {
            get {
                return ResourceManager.GetString("TW_trainingDeletionPromptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ану вводь нову назву тренування! І щоб щось крім пробілів було!.
        /// </summary>
        public static string TW_trainingTitleErrorMessage {
            get {
                return ResourceManager.GetString("TW_trainingTitleErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Що за чортівня? Щось дивне трапилось при спробі запису даних. Ану спробуй ще раз.
        /// </summary>
        public static string TW_unknownSavingErrorMessage {
            get {
                return ResourceManager.GetString("TW_unknownSavingErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Та щоб його! Помилка зберігання.
        /// </summary>
        public static string TW_unknownSavingErrorTitle {
            get {
                return ResourceManager.GetString("TW_unknownSavingErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тренування (ой, як же епічно звучить).
        /// </summary>
        public static string TW_windowTitle {
            get {
                return ResourceManager.GetString("TW_windowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Агов, схаменися! Неправильний ввід.
        /// </summary>
        public static string wrongInputTitle {
            get {
                return ResourceManager.GetString("wrongInputTitle", resourceCulture);
            }
        }
    }
}
